### ISSUE TITLE
Nice work！But, when will the inference code be released

### ISSUE THREAD

**Issue by hellozhengzhengyou** [ShengCN/SSN_SoftShadowNet#4]

**Comment by ShengCN** [comment]
Hi, thank you for the interest! Here is the demo page: https://huggingface.co/spaces/ysheng/SSN-Soft-Shadow-Network-for-Image-Composition. 

I am wrapping up all the codes together. It should be out soon.

**Comment by LukaGiorgadze** [comment]
@ShengCN any updates? Huggingface does not work. 
Thanks!

**Comment by ShengCN** [comment]
I have released the inference code now. Take a look!
